export const textInputsAddCompetition = [
    {
      id: 0,
      label: "Name",
      value: "name",
      type: "text",
      multiline: false,
      required: true,
    },
    {
      id: 3,
      label: "Country",
      value: "country",
      type: "text",
      multiline: false,
      required: true,
    },
    {
      id: 4,
      label: "Location",
      value: "location",
      type: "text",
      multiline: false,
      required: true,
    },
    {
      id: 5,
      label: "Anvils avalible",
      value: "anvils",
      type: "number",
      multiline: false,
      required: true,
    },
    {
      id: 6,
      label: "",
      value: "dateFrom",
      type: "date",
      multiline: false,
      required: true,
    },
    {
      id: 7,
      label: "",
      value: "dateTo",
      type: "date",
      multiline: false,
      required: true,
    },
    {
      id: 8,
      label: "Hotels",
      value: "hotels",
      type: "text",
      multiline: true,
      required: false,
    },
    {
      id: 9,
      label: "Parking",
      value: "parking",
      type: "text",
      multiline: true,
      required: false,
    },
    {
      id: 10,
      label: "Other information",
      value: "information",
      type: "text",
      multiline: true,
      required: false,
    },
  ];
  
  export const divisionDataAddCompetition = [
    {
      id: 11,
      label: "Semi final spaces",
      value: "semi",
      type: "number",
      multiline: false,
      required: false,
    },
    {
      id: 12,
      label: "Final spaces",
      value: "final",
      type: "number",
      multiline: false,
      required: false,
    },
  ];

  export const textFieldsRegister = [
    {
      id: 1,
      label: "Name",
      type: "text",
      key: "name",
    },
    {
      id: 2,
      label: "Age",
      type: "number",
      key: "age",
    },
    {
      id: 3,
      label: "Address",
      type: "text",
      key: "address",
    },
    {
      id: 4,
      label: "Phone number",
      type: "number",
      key: "phone",
    },
    {
      id: 5,
      label: "Country",
      type: "text",
      key: "country",
    },
    {
      id: 6,
      label: "",
      type: "file",
      key: "img",
    },
  ];
 
 export const textInputsEditCompetition = [
    {
      id: 0,
      label: "Name",
      value: "name",
      type: "text",
      multiline: false,
    },
    {
      id: 3,
      label: "Country",
      value: "country",
      type: "text",
      multiline: false,
    },
    {
      id: 4,
      label: "Location",
      value: "location",
      type: "text",
      multiline: false,
    },
    {
      id: 5,
      label: "Anvils avalible",
      value: "anvils",
      type: "number",
      multiline: false,
    },
    {
      id: 6,
      label: "",
      value: "dateFrom",
      type: "date",
      multiline: false,
    },
    {
      id: 7,
      label: "",
      value: "dateTo",
      type: "date",
      multiline: false,
    },
    {
      id: 8,
      label: "Hotels",
      value: "hotels",
      type: "text",
      multiline: true,
    },
    {
      id: 9,
      label: "Parking",
      value: "parking",
      type: "text",
      multiline: true,
    },
    {
      id: 10,
      label: "Other information",
      value: "information",
      type: "text",
      multiline: true,
    },
  ]; 